### ISSUE TITLE
Support migration from v1alpha1 to v1alpha2 OAM CRDs

### ISSUE THREAD

**Issue by hongchaodeng** [crossplane/oam-kubernetes-runtime#108]
# Background
There are many many existing users who adopted v1alpha1. In order for them to adopt oam-k8s-runtime and upgrade to v1alpha2 spec, they need to migrate existing OAM CRDs and objects.

The migration could be done via automatic conversion provided as a webhook. For more details, please refer to [upstream doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/).

# What to do in OAM Runtime
OAM Runtime could support the migration logic and expose a HTTP port as webhook.

This diagram depicts the overall workflow:

![migrate](https://user-images.githubusercontent.com/920884/87825029-3796cc80-c82b-11ea-8adb-cae15507b58f.png)

**Comment by resouer** [comment]
Related: https://github.com/vmware/crd-migration-tool

**Comment by hongchaodeng** [comment]
https://quanxi-account.aliyun-inc.com/


For next steps, we need to write tools to automate two kinds of migration:

1. APIVersion migration.

    - [Change v1beta1 CRD definition to v1 CRD](https://github.com/crossplane/oam-kubernetes-runtime/issues/118).
    - We need to add a Kustomize Overlay of v1alpha1 OAM Types to existing v1alpha2 OAM Types:

      ```yaml
      versions:
      - name: v1alpha1
        served: true
        storage: false
        schema:
          ...
      ```

      Additionally, we need to add the following overlay to AppConfig CRD:

      ```yaml
      conversion:
        strategy: Webhook
      ```

      This will call the webhook when API calls for v1alpha1 come.

    - Write the webhook server that does the conversion from v1alpha1 to v1alpha2. Here is [an example](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#write-a-conversion-webhook-server).

    - Deploy and test the webhook server.

2. StorageVersion migration.

    - Existig AppConfigs might be stored as v1alpha1 format. We need to upgrade them into v1alpha2 format in storage.
      There is a trick that we can just list them and then apply them again in new storage version.
    - More format process and tooling has been [documented here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version).

**Comment by hongchaodeng** [comment]
Here is some diagrams depicting more details for the migration:

## 1. Implement and deploy conversion webhook
  - It is used to support not only user requests but also the storage migration too
  - Need to support not only AppConfig conversion but also some custom logic to update Components too

![20200729190155](https://user-images.githubusercontent.com/920884/88871994-17252580-d1ce-11ea-89f2-c8be4e293848.jpg)

## 2. Deploy storage version migrator to automatically migrate existing data

![20200729190027](https://user-images.githubusercontent.com/920884/88872093-4dfb3b80-d1ce-11ea-93a7-3e4b16107d8c.jpg)

**Comment by wonderflow** [comment]
What's the state of this issue now? Have we finished or not? @hongchaodeng

**Comment by hongchaodeng** [comment]
Yes. It is been implemented in project: https://github.com/oam-dev/oam-crd-migration
