### ISSUE TITLE
[proposal] Component and Trait Dependency

### ISSUE THREAD

**Issue by hongchaodeng** [crossplane/oam-kubernetes-runtime#11]
# Background

This is an extension from https://github.com/oam-dev/spec/pull/326. Create the issue here to acquire more interest. We also have an implementation in our fork so we would like to merge them together.

Let me start with three use cases here.

## 1. Web app depends on database

An applicationConfiguration consists of two components: web and db. Web component should not be created until db component is created and ready, including database account and public endpoint created and ready.

## 2. ML app workflow

An ML applicationConfiguration has three components:

- preprocess
- training
- serving

They have strict ordering as follows:

```
  preprocess -> training -> serving
```

Without the previous stage finished, the next could not start due to lack of data.
Today, ML framework including Tensorflow would not handle such dependency health. They rely on external platform to handle it.

## 3. Service binding trait

More background info on service binding can be found here: [slides](https://docs.google.com/presentation/d/1PseN_8_zZH8clWZJzP8tuRMpz51SxQb-mKeG1f4QVZQ/edit?usp=sharing).
A service binding trait needs to be applied before creating the component.
Moreover, this trait ordering use case is quite general and applies to many other traits we have.

**Comment by hongchaodeng** [comment]
cc @vturecek @negz @artursouza @resouer @wonderflow @ryanzhang-oss

**Comment by wonderflow** [comment]
Totally agree!  Component and Trait Dependency are really important and needed! Let me add one more scenario.

# Scenario : workload which can run without everything is ready 

Let's say we have a containerized workload and log collector trait.
If we don't have trait order, the workload could run smoothly and can't feel that log collector isn't ready. Then we may miss some audit logs. If these audit logs are really important, we must need the trait to start before the workload start.

**Comment by allenhaozi** [comment]
We are building new machine learning scenarios internally, We call it [Hypercycle ML](http://www.4paradigm.com/product/hypercycleml)
a completed hypercycle  requires multiple services composed and these services is ordered
this  dependency can help us build a lighter infrastructure and low coupling platform

**Comment by wonderflow** [comment]
closing as proposal has been merged and implemented https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/resource-dependency.md
