### ISSUE TITLE
VolumeResource.MouthPath typo in core_workload_types 

### ISSUE THREAD

**Issue by helios741** [crossplane/oam-kubernetes-runtime#120]
[v1alpha2/core_workload_types.go#L113](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/apis/core/v1alpha2/core_workload_types.go#L113) field is **MouthPath**, But json is **mountPath**,Is it a spelling mistake?If it is, I can create a PR to fix it.

**Comment by hongchaodeng** [comment]
Should be `MountPath`

**Comment by wonderflow** [comment]
fixed by #122
