### ISSUE TITLE
CI fail for PR

### ISSUE THREAD

**Issue by helios741** [crossplane/oam-kubernetes-runtime#124]
i submitted  [pr](https://github.com/crossplane/oam-kubernetes-runtime/pull/122#partial-pull-merging) , but continuous-integration/jenkins/pr-head  error , is [this](https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Foam-kubernetes-runtime/detail/PR-122/2/pipeline) error.
![image](https://user-images.githubusercontent.com/12036324/88245672-8a103700-ccca-11ea-8faa-4e6d88fefae1.png)
This is obviously not a problem with my code, please troubleshoot.I think RERUN is enough, but I can't find the button.

**Comment by hongchaodeng** [comment]
As maintainers we can't rerun the tests by now. Still figuring out a way to do that.
cc @jbw976 @hasheddan 

@helios741 At the mean time, how about just amend the commit message and force push it again to retrigger?
