### ISSUE TITLE
Honor the AppliesTo field in the trait

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#14]
The current AC controller implementation doesn't look up to a trait's TraitDefinition CR when it applies a trait to a workload. We need to throw an error if the workload is not part of the 'appliesTo' field.

**Comment by wonderflow** [comment]
I think this need to be done on admission webhook. Do we have a existing webhook project for crossplane? @negz

**Comment by wonderflow** [comment]
Now we have admission controller, this work would be easily done.

**Comment by captainroy-hy** [comment]
I would like to helo on this issue as well as #50.
