### ISSUE TITLE
Use one client in appConfig controller to keep code concise

### ISSUE THREAD

**Issue by captainroy-hy** [crossplane/oam-kubernetes-runtime#152]
In AppConfig controller [Reconciler](https://github.com/crossplane/oam-kubernetes-runtime/blob/ca3bc22d767e0a67da3eeb8bc07360916f544d8d/pkg/controller/v1alpha2/applicationconfiguration/applicationconfiguration.go#L167) and [Component Handler](https://github.com/crossplane/oam-kubernetes-runtime/blob/ca3bc22d767e0a67da3eeb8bc07360916f544d8d/pkg/controller/v1alpha2/applicationconfiguration/applicationconfiguration.go#L84), there are two clients instantiated, one is controller-runtime client used to deal with multiple resources, the other one is client-go client only used to handle ControllerRevision resource here. 

Since controller-runtime client also can deal with ControllerRevision as what client-go client does([create](https://github.com/crossplane/oam-kubernetes-runtime/blob/ca3bc22d767e0a67da3eeb8bc07360916f544d8d/pkg/controller/v1alpha2/applicationconfiguration/component.go#L171)&[get](https://github.com/crossplane/oam-kubernetes-runtime/blob/ca3bc22d767e0a67da3eeb8bc07360916f544d8d/pkg/controller/v1alpha2/applicationconfiguration/component.go#L103)), we could just keep controller-runtime client instead of both to keep code concise.

**Comment by wonderflow** [comment]
re-assign to @erdun as he is already working on it #95

**Comment by captainroy-hy** [comment]
Sure, got it.

**Comment by wonderflow** [comment]
fixed by #155
