### ISSUE TITLE
[BUG] Write e2e test for CRUD of TraitDefinition/WorkloadDefinition/ScopeDefinition with spec.extension field

### ISSUE THREAD

**Issue by zzxwill** [crossplane/oam-kubernetes-runtime#156]
**Describe the bug**

As a new field `spec.extension` is added  to TraitDefinition/WorkloadDefinition/ScopeDefinition, CRUD is need for the e2e-test.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

**Comment by zzxwill** [comment]
Please help assign this to me.

**Comment by wonderflow** [comment]
we will not write test here
