### ISSUE TITLE
[BUG] Scope workload-ref records not removed when referenced AppConfig deleted

### ISSUE THREAD

**Issue by captainroy-hy** [crossplane/oam-kubernetes-runtime#158]
**Describe the bug**

Scope, e.g. Healthscope, records referenced workloads in its workloadRefsPath field, if we delete ref workloads' owner appConfig, the workload would be gc but its record in Scope would NOT. **The root problem** is that, delete operation on AppConfig cannot trigger [`dereferenceScope` ](https://github.com/crossplane/oam-kubernetes-runtime/blob/be76681896c9ec86525815c32b11d19e218432d9/pkg/controller/v1alpha2/applicationconfiguration/apply.go#L113) meanwhile scope controller has no awareness of AppConfig is gone. 

For Healthscope, since it can not get the workload at more, "Unhealthy" turns out but it doesn't make sense.

It's a bit similar to #67, even though that's another scenario. 

**To Reproduce**
1. Apply ./examples/containerized-workload/ and check `example-health-scope` spec
It contains `example-appconfig-workload` worload and the scope is healthy.
2. `kubectl delete appconfig example-appconfig` and then check scope spec again
It still contains `example-appconfig-workload` and the scope is unhealthy.

**Possible solution**

Maybe AppConfig webhook on Delete operation can help?

**Comment by wonderflow** [comment]
We can use [finalizer](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers) to solve this issue. Usually the steps could be as following:

1. When scope is attached to an AppConfig, mark a finalizer on it.
2. When AppConfig is deleting, the finalizer will stop K8s apiserver from really deleting. Instead, apiserver will mark a deletionTimestamp and trigger an event to let controller of AppConfig clean the finalizer.
3. The controller of AppConfig will get the event and do garbage collection，and finally remove the finalizer.
4. After the finalizer removed, apiserver will clean the object.

**Comment by captainroy-hy** [comment]
@wonderflow Got it! Could you please assign this issue to me?

**Comment by hongchaodeng** [comment]
assigned @captainroy-hy

**Comment by captainroy-hy** [comment]
Fixed in #163
