### ISSUE TITLE
[Feature] Monolithic is preferred in OAM runtime

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#176]
**Is your feature request related to a problem? Please describe.**

Having multiple controllers installed and maintained doesn't make sense, as they are all core features of OAM, like rollout, monitoring, logging, route etc. We should think about how to go monolithic.

**Describe the solution you'd like**

Package all core/standard workload/trait in OAM Kubernetes Runtime, with a ConfigMap to set if want to disable some of them.

(Optional): we can also think about deprecate "standard" category to make this decision easier, see: https://github.com/oam-dev/spec/issues/391

/cc @ryanzhang-oss @hongchaodeng @wonderflow

**Comment by ryanzhang-oss** [comment]
We haven't really designated any resources as "standard"  yet.

**Comment by resouer** [comment]
@ryanzhang-oss Metrics Trait? https://github.com/oam-dev/catalog/tree/master/traits/metricstrait

**Comment by negz** [comment]
> Having multiple controllers installed and maintained doesn't make sense.

This is a little confusing - do you mean multiple controller _managers_ (e.g. multiple pods, or multiple deployments?). I assume we do not to reduce the amount of controllers (e.g. reconcile loops) used to power OAM.

**Comment by resouer** [comment]
@negz I mean multiple deployments. Though this issue is not valid any more. Close it.
