### ISSUE TITLE
Namespace scope support

### ISSUE THREAD

**Issue by draveness** [crossplane/oam-kubernetes-runtime#18]
Are we going to add a scope to change the namespace of a kubernetes object?

https://github.com/crossplane/oam-kubernetes-runtime/blob/6b9e040ab7ec1f68b6df4476fad1e18606c9ecb1/pkg/workload/containerized/containerized.go#L62-L65

**Comment by wonderflow** [comment]
What @hasheddan means is not changing the namespace of an existing kubernetes object. I think he means before a k8s object being create, the controller could use namespace scope to know which namespace the k8s object will go.

**Comment by draveness** [comment]
> What @hasheddan means is not changing the namespace of an existing kubernetes object. I think he means before a k8s object being create, the controller could use namespace scope to know which namespace the k8s object will go.

Does it mean that the controller doesn't know the namespace of an kubernetes object, why not read the metadata field of an object?

**Comment by wonderflow** [comment]
This issue occurs in multi-cluster cases, one Application deployed in a master cluster will need some child parts which need to be deployed in remote clusters. The object in remote cluster need to know their namespace.

**Comment by draveness** [comment]
> This issue occurs in multi-cluster cases, one Application deployed in a master cluster will need some child parts which need to be deployed in remote clusters. The object in remote cluster need to know their namespace.

SGTM, thanks for the clarification.
