### ISSUE TITLE
nominate @captainroy-hy（individual contributor） as the new oam-k8s-runtime maintainer

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#219]
During the last three months, @captainroy-hy as an individual contributor, contributes a lot to this project including bug fix, enhancement, feature. And now, he's one of the top contributors in this project.

He's also glad to invest more time into this project in the long term. So I'm glad to nominate him as the new oam-k8s-runtime project maintainer, let's build our project better and make it popular. He will take [the responsibilities of maintainers](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#maintainers).

Hi @captainroy-hy, Please feel free to reply accept/reject for this nomination.

After that, ping @negz @hasheddan @hongchaodeng @ryanzhang-oss  , please feel free to +1 in the comment if you endorse this nomination, and feel free to raise objection if there's any concern (the nomination would hold in this case).

**Comment by captainroy-hy** [comment]
I'm glad to accept it. It would be my great pleasure to be a maintainer and to contribute more to this great project! 
@negz @hasheddan @hongchaodeng @ryanzhang-oss

**Comment by hongchaodeng** [comment]
dominate -> nominate

+1 from me.
Thanks for the contribution and look forward to future collaboration.

**Comment by ryanzhang-oss** [comment]
+1

**Comment by wonderflow** [comment]
ping @negz @hasheddan

**Comment by hasheddan** [comment]
+1 thanks for the great contributions you have already made @captainroy-hy!
