### ISSUE TITLE
Workload type choice support

### ISSUE THREAD

**Issue by pigletfly** [crossplane/oam-kubernetes-runtime#22]
why we are using Deployment? Can we use other kinds of kubernetes workload type? such as StatefulSet.

**Comment by ryanzhang-oss** [comment]
IIRC, this is a similar request to https://github.com/crossplane/oam-kubernetes-runtime/issues/13. I wonder if our responses, especially https://github.com/crossplane/oam-kubernetes-runtime/issues/13#issuecomment-622176013, answer your question?

**Comment by ryanzhang-oss** [comment]
You are more than welcome to propose a StatefulSet workload type.

**Comment by ryanzhang-oss** [comment]
close this as it's a duplicate of  #13
