### ISSUE TITLE
Question on Service Type

### ISSUE THREAD

**Issue by pdettori** [crossplane/oam-kubernetes-runtime#221]
The `ContainerizedWorkload` generates a `Service` with type `NodePort`. It looks like this is currently hardcoded in the  `renderService` function. Are there plans to allow supporting other types of services ? E.g. what if I need only a service of type `ClusterIP` ?

**Comment by resouer** [comment]
@pdettori Yes. For kubernetes implementation, we'll move to use another workload implementation, [please check it here](https://github.com/oam-dev/kubevela/blob/97f4d516fb2ace7dce6cbc2057ba18e26dd24c21/pkg/controller/v1alpha1/containerized/containerized_controller.go#L208). Service type is configurable during the OAM app platform init there. We will add the new workload schema as part of OAM spec in next spec release.

In case you are curious, KubeVela is a full app platform implementation of OAM and it imports this runtime as dependency. The plan is we'll keep this repo focus on building block primitives of OAM such as component and appconfig, and move workload/trait controllers there.

**Comment by pdettori** [comment]
Thank you @resouer, this helps.
