### ISSUE TITLE
Add race detector to go test flags

### ISSUE THREAD

**Issue by hongchaodeng** [crossplane/oam-kubernetes-runtime#256]
We are trying to add `-race` to go test in OAM related projects.
We haven't figured out how to do it in the crossplane build scripts. Creating this issue to gather help.

**Comment by hongchaodeng** [comment]
cc @jbw976 @hasheddan @negz

**Comment by jbw976** [comment]
Hi @hongchaodeng, there is a `GO_TEST_FLAGS` var defined in `golang.mk` that should help here.  https://github.com/upbound/build/blob/master/makelib/golang.mk#L35

It looks like it's passed to the invocation of `go test`.  So maybe around https://github.com/crossplane/oam-kubernetes-runtime/blob/master/Makefile#L44, you can add the following?

```
GO_TEST_FLAGS += -race
```

**Comment by wonderflow** [comment]
@jbw976  Hi, it seems the unit test don't support race flag https://github.com/upbound/build/blob/master/makelib/golang.mk#L174

```
-covermode must be "atomic", not "count", when -race is enabled
```

How can we fix this ?

\cc @hasheddan @negz

**Comment by negz** [comment]
I suggest opening a PR against upbound/build to make the covermode configurable. Count and atomic are similar, but count is faster when the race detector is not desired.

**Comment by wonderflow** [comment]
@negz  I'm not very familiar with makefile shell, could you help add that PR on upbound/build, thanks!

**Comment by wonderflow** [comment]
I have tried to send a PR https://github.com/upbound/build/pull/125 , please help review thanks @negz
