### ISSUE TITLE
Traits candidate list to complete the picture

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#26]
Listed by priority from high to low:

1. Ingress
2. Autoscaler
3. Rollout (Flagger based)

Feel free to propose more.

**Comment by ryanzhang-oss** [comment]
For ingress, can we start with [simple ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress)?
Or we want to bring a more powerful one like Istio?

**Comment by resouer** [comment]
@ryanzhang-oss A simple ingress, though we should define the definition better than demo.

Here's a super list of ingress controllers: https://docs.google.com/spreadsheets/d/1xjff2AMS6QXSdh8E8ay_uNMoUa2OLIanCallvkDvAy0/edit#gid=0

Isito is for more complex cases like traffic mgmt etc.

**Comment by wonderflow** [comment]
* Service Trait （K8s Service）
* Container Resource Quota Trait （fields of pod template）
* VolumeMount Trait (pv/pvc)
* Monitoring Trait  (Prometheus)
* Log Trait （ELK）

**Comment by wonderflow** [comment]
I'm closing this issue here since we're implementing them in [vela](https://github.com/oam-dev/kubevela)
