### ISSUE TITLE
ManualScalerTrait support update resource 

### ISSUE THREAD

**Issue by allenhaozi** [crossplane/oam-kubernetes-runtime#27]
Is it appropriate if ManualScalerTrait can update the container resource ? 
```
// A ManualScalerTraitSpec defines the desired state of a ManualScalerTrait.
type ManualScalerTraitSpec struct {
	// ReplicaCount of the workload this trait applies to.
	ReplicaCount int32 `json:"replicaCount"`
        // container resource request
        ResourceRequest ContainerResources `json:"resourceRequest"` 
        // container resource limit
        ResourceLimit ContainerResources `json:"resourceLimit"`
	// WorkloadReference to the workload this trait applies to.
	WorkloadReference runtimev1alpha1.TypedReference `json:"workloadRef"`
}
```

1. scaling itself is related to resources
2. In some cases, the user want more replicas, but the resource of the instance can be lowered
3. only when the user passes in a valid value will we update the corresponding value
4. It's easier to maintain one than two

**Comment by ryanzhang-oss** [comment]
Thanks, @allenhaozi.  
Can you elaborate on what does "support update resource" mean? 
I am not sure if we have a ResourceRequest type already?   Can you spell out its semantics a bit more?
The same applies to the ResourceLimit.

**Comment by allenhaozi** [comment]
> Thanks, @allenhaozi.
> Can you elaborate on what does "support update resource" mean?
> I am not sure if we have a ResourceRequest type already? Can you spell out its semantics a bit more?
> The same applies to the ResourceLimit.

the definition of resource is here: [https://github.com/crossplane/oam-kubernetes-runtime/blob/master/apis/core/v1alpha2/core_workload_types.go#L144](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/apis/core/v1alpha2/core_workload_types.go#L144)

**Comment by ryanzhang-oss** [comment]
Close it, for now.  Feel free to open it when we have a clear use case.
