### ISSUE TITLE
[Feature] support don't reconcile if AppConfig or Component not updated

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#277]
**Is your feature request related to a problem? Please describe.**

Currently, OAM runtime will reconcile periodically, this mechanism can help CR always working as expected ( unexpected changes will be reconciled back periodically)

But it will introduce some risks especially when the oam-runtime Controller was just upgraded.

**Describe the solution you'd like**

I hope we can add a switch on oam-runtime, by default the switch is turned off, it will work as it is now. If the switch is turned on, the controller will check AppConfig generation, if generation is the same with status.observedGeneration and the condition is ready, it will not reconcile.

**Comment by captainroy-hy** [comment]
I would like to work on this issue.
