### ISSUE TITLE
 [Feature] make development log setting as an argument

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#284]
![image](https://user-images.githubusercontent.com/2173670/98340167-e748b200-2047-11eb-9bd9-d0f653b7a0aa.png)

Currently the development flag is always true, so we will get lot's of debug log by default.

I think we should make the default development flag to be false, and add a command in Makefile such as `make debug-run` to switch the flag on.

**Comment by BH4AWS** [comment]
ctrl.SetLogger方法内，建议o.Development默认采用False，并引入一个flag标识，通过变量参数形式传入确认。

pr正在准备中，待提交review。

**Comment by kushthedude** [comment]
Hi @wonderflow, I am working on this issue!
