### ISSUE TITLE
[Feature] using trait type instead of hardcode word 'trait' to create trait CR

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#294]
![image](https://user-images.githubusercontent.com/2173670/98787273-42104e00-243a-11eb-96d6-85c40700602e.png)

```
$ kubectl get routes.standard.oam.dev
NAME                     AGE
myweb-trait-6ccc7c55c5   63m
testapp-trait-998b8f6f   46h
```

## Expect behavior

```
$ kubectl get routes.standard.oam.dev
NAME                     AGE
myweb-route-6ccc7c55c5   63m
testapp-route-998b8f6f   46h
```

**Comment by zzxwill** [comment]
Please help assign it to me.

**Comment by wonderflow** [comment]
@zzxwill  please make sure this is a compatible upgrade, which means, if user has already created a trait with the old naming rule and the spec didn't change , use the old name. Only the newly created trait will have the new name.
