### ISSUE TITLE
Tracker: reorganize OAM related code and repo

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#55]
Per discussion on previous community meeting and offline discussion in slack, we will merge OAM related code and repos into one and give it an independent release. It would be much easier to maintain after this re-org.

Tracking steps:

1. Merge https://github.com/crossplane/addon-oam-kubernetes-local into oam-kubernetes-runtime
2. Give oam-kubernetes-runtime a release (runnable controller with independent release version), add documentation for it
3. Refactor the existing documentation of crossplane.io
4. Deprecate https://github.com/oam-dev/crossplane-oam-sample in favor of this merge
4. Deprecate https://github.com/crossplane/addon-oam-kubernetes-remote in favor of deprecation of KubernetesApplication

/cc @ryanzhang-oss @wonderflow @hongchaodeng @zzxwill @negz

**Comment by ryanzhang-oss** [comment]
First step
https://github.com/crossplane/oam-kubernetes-runtime/pull/63

**Comment by wonderflow** [comment]
Step 4 has done https://github.com/oam-dev/crossplane-oam-sample

**Comment by wonderflow** [comment]
closing as all related things has been done in this issue
