### ISSUE TITLE
Give TraitDefinition/WorkloadDefinition a short name?

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#57]
xref: https://github.com/oam-dev/spec/issues/331#issuecomment-604787669

I am thinking maybe we can give them a short name like "trait" and "workload"? 

I feel my fingers are trembling after CRUD `traitdefinitions` and `workloaddefinitions` for several times, they are just too long and verbose to type in even with best keyboard.

/cc @negz

**Comment by wonderflow** [comment]
Closing as we have already decouple Definition Name with  CRD, so we could just use definition name as the "short" name.
