### ISSUE TITLE
Support OAM's HealthScope

### ISSUE THREAD

**Issue by artursouza** [crossplane/oam-kubernetes-runtime#58]
### What problem are you facing?
OAM's HealthScope is not supported in Crossplane.

### How could Crossplane help solve your problem?
Support HealthScope, similar to Rudr:

https://github.com/oam-dev/rudr/tree/master/healthscope

Parent: crossplane/crossplane#1480

**Comment by ryanzhang-oss** [comment]
duplicate https://github.com/crossplane/oam-kubernetes-runtime/issues/61
