### ISSUE TITLE
Implement ApplicationScope in Crossplane

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#62]
### What problem are you facing?
We didn't find concrete use case for [Scope](https://github.com/oam-dev/spec/blob/master/5.application_scopes.md)  concept on K8s before so we decide to skip it temporarily in Crossplane. Though we now found Scope is actually a strong need for traffic mgmt in app. For example the [Istio BookInfo sample](https://github.com/istio/istio/tree/master/samples/bookinfo) should be able to be modeled easily with Crossplane's application model.

The mapping would be:

- _Component_ - Deployment
- _Trait_ - Service/Ingress per Deployment
- _Scope_ - Service/Ingress/APIGateway across Deployments
- _ApplicationConfiguration_ - a YAML file to grouping Component/Trait/Scope together

Mirror issue: https://github.com/oam-dev/rudr/issues/558#issuecomment-622186672

### How could Crossplane help solve your problem?
Implement [Scope](https://github.com/oam-dev/spec/blob/master/5.application_scopes.md) feature in [Crossplane's application model](https://github.com/crossplane/oam-kubernetes-runtime).

/cc @omkensey @ryanzhang-oss

**Comment by ryanzhang-oss** [comment]
@artursouza can we close this issue now?

**Comment by artursouza** [comment]
We did implement HealthScope. If this issue is about other Application Scopes too, then it should remain open.

**Comment by wonderflow** [comment]
Let's close this issue as health scope already be implemented as a good example about how to implement Application Scopes. Feel free to create a new one if new scopes are needed.
