### ISSUE TITLE
Make the default trait name not the same as the component name

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#66]
Currently, we use the component name as the trait name in the `setTraitProperties` function. It will be good for the name to indicate that it belongs to a `trait`

**Comment by Ghostbaby** [comment]
@ryanzhang-oss Please assign to me.

**Comment by ryanzhang-oss** [comment]
> @ryanzhang-oss Please assign it to me.

Thank you very much for your help. Looks like you have successfully assigned it to yourself. Please create a pull request when you are ready
