### ISSUE TITLE
improve health scope implementation

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#68]
The health scope currently only works with containerizedWorkload. 
- We should make it work with any workload 
-  Add more unit test to bring the code coverage to at least 90%

**Comment by captainroy-hy** [comment]
Maybe I can help on this issue. Could you please assign it to me? @ryanzhang-oss

**Comment by wonderflow** [comment]
I think we could close this issue, thanks to @captainroy-hy
