### ISSUE TITLE
app-config pass labels and annotation to workload and trait 

### ISSUE THREAD

**Issue by allenhaozi** [crossplane/oam-kubernetes-runtime#77]
Internally, there are scenarios where we need to get corresponding Annotation information in the Controller of the Workload and trait, so we can do some business processing based on the annotations, such as namespace isolation
Workload and trait only processing those workload and traits where the information in the Annotation meets the conditions

If app-config can pass this information, it's very convenient, You can write generic annotations to Workload and traits without having to write them intentionally, In particular, writing workload annotations in app-config is a little more complicated

**Comment by wonderflow** [comment]
I think it make sense to pass through labels and annotations from Appconfig into workload and traits.

**Comment by wonderflow** [comment]
I've discussed with @allenhaozi  and he's glad to send a PR. Thanks!
