### ISSUE TITLE
change ingress yaml in flight-tracker example to ingress trait

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#79]
In our [flight-tracker example](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/flight-tracker/), ingress is still installed as a standalone yaml file, it should be trait.

**Comment by sunny0826** [comment]
IngressTrait need [`IngressTrait controller`](https://github.com/oam-dev/catalog/tree/master/traits/ingresstrait), but it may not in `oam-kubernetes-runtime`

**Comment by wonderflow** [comment]
@sunny0826  We can use Ingress directly without using `IngressTrait` CRD.
