### ISSUE TITLE
some problem of dependency README.md

### ISSUE THREAD

**Issue by sunny0826** [crossplane/oam-kubernetes-runtime#93]
https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/dependency/README.md

may need remove `Start OAM runtime by: ...`
![image](https://user-images.githubusercontent.com/24563928/87114132-639dd500-c2a2-11ea-991b-1f841da5e5bd.png)

need add deploy [`crd`](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/dependency/crd.yaml) and [`TraitDefinition`](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/dependency/trait-definition.yaml) doc.

**Comment by hongchaodeng** [comment]
This will be fixed in https://github.com/crossplane/oam-kubernetes-runtime/pull/74

**Comment by sunny0826** [comment]
cool !

**Comment by wonderflow** [comment]
closing as #74 merged
