### ISSUE TITLE
Componet not shared with namespaces

### ISSUE THREAD

**Issue by erdun** [crossplane/oam-kubernetes-runtime#94]
Componet not shared in namespaces, must create component in each namespaces. Should appConfig use component cross namespaces?

**Comment by resouer** [comment]
Unfortunately, K8s won't allow you to reference resource across namespaces.

**Comment by Ghostbaby** [comment]
Maybe, you can use the svc name to connect another namespace component.

**Comment by erdun** [comment]
Creating components each namespaces，components operations must create components before the end users use, if there are many namepsaces, maintaining components or traits may be a dirty work, is it possible use labels to refer the resource?

**Comment by wonderflow** [comment]
In which case do you need to share components in different namespaces? It will be helpful if you could describe a bit more details.

**Comment by erdun** [comment]
Each team is permitted in one namespace in our company, so there're several namespaces. As the admin of the cluster, I need create components in each namespace first that they can create Appconfig in there's namespaces. Or is there any recommend ways to use oam?

**Comment by wonderflow** [comment]
Component should be created by user not admin, they are instances of an App not template.
