### ISSUE TITLE
Upload charts to Helm Hub?

### ISSUE THREAD

**Issue by majian159** [crossplane/oam-kubernetes-runtime#97]
After uploading to helm, git clone is no longer needed.

**Comment by wonderflow** [comment]
Yeah, we're integrating this repo into crossplane release https://github.com/crossplane/oam-kubernetes-runtime/pull/90

After that, the helm chart will generate automatically.

**Comment by wonderflow** [comment]
released https://github.com/crossplane/oam-kubernetes-runtime#install-oam-runtime
